### ISSUE TITLE
give same result for every page

### ISSUE THREAD

**Issue by blackhydra163** [shaheenfazim/url-scraper#3]
I chose 2: BING SEARCH
 and
[i] Enter query: site:example.com
[x] Enter page count: 5

In the output, it gives me the same result for every page.

**Comment by shaheenfazim** [comment]
It's because there is nothing more to crawl for the site example.com by the search engine (Bing Search). Have you tried with another site that has more links, and therefore provides more results (e.g., site: google.com)? If you still believe the same problem exists, please ping me. For now, I am closing this as fixed. Thank you.
